#!/usr/bin/env python3
"""Assembler for the mini RTS trigger-script VM (see src/Script.cpp).

Turns tools/map_script.asm into src/MapScript.cpp, a plain byte array the
game loads at startup. Only the bytes end up in the binary; names, labels
and comments stay here.

Usage:
    python tools/script_asm.py tools/map_script.asm src/MapScript.cpp

Syntax:
    ; comment
    .globals N
    .func name num_args num_locals
    label:
        op [operand]
    .endfunc

Operands: integers, floats, labels (jumps), function names (call, and
`pushi @name` for a function index), native names (native NAME argc).
"""

import struct
import sys

OPCODES = {
    "nop": 0x00, "pushi": 0x0C, "pushf": 0x0D,
    "ldg": 0x11, "stg": 0x12, "ldl": 0x13, "stl": 0x14,
    "add": 0x20, "sub": 0x21, "mul": 0x22, "div": 0x23, "mod": 0x24, "neg": 0x25,
    "lt": 0x30, "le": 0x31, "gt": 0x32, "ge": 0x33, "eq": 0x34, "ne": 0x35,
    "and": 0x36, "or": 0x37, "not": 0x38,
    "jmp": 0x40, "jz": 0x41, "jnz": 0x42,
    "call": 0x50, "native": 0x51, "ret": 0x52, "retv": 0x53,
    "pop": 0x60, "dup": 0x61, "i2f": 0x62, "f2i": 0x63, "halt": 0x7F,
}

# Must match the order of g_scriptNatives in src/Script.cpp.
NATIVES = [
    "GetGameTime", "GetRandomInt", "GetRandomReal", "CreateUnit", "KillUnit",
    "GetUnitLife", "SetUnitLife", "GetTriggerUnit", "GetKillingUnit",
    "GetOwningPlayer", "AddPlayerGold", "AddPlayerLumber", "GetPlayerGold",
    "GetUnitTypeId", "GetUnitX", "GetUnitY", "IssuePointOrder",
    "CountPlayerStructures", "SetPlayerDefeated", "IsPlayerDefeated",
    "CreateItem", "RegisterTimerTrigger", "RegisterDeathTrigger", "GetStartX",
    "GetStartY", "GetUnitLevel", "IsUnitHero", "GetTimeOfDay",
    "GetPlayerCount", "EndGame",
]

SIZES = {"pushi": 5, "pushf": 5, "ldg": 2, "stg": 2, "ldl": 2, "stl": 2,
         "jmp": 3, "jz": 3, "jnz": 3, "call": 2, "native": 3}


class Func:
    def __init__(self, name, nargs, nlocals):
        self.name = name
        self.nargs = nargs
        self.nlocals = nlocals
        self.lines = []  # (lineno, op, args)
        self.labels = {}


def parse(path):
    globals_count = 0
    funcs = []
    cur = None
    with open(path) as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.split(";", 1)[0].strip()
            if not line:
                continue
            if line.startswith(".globals"):
                globals_count = int(line.split()[1])
            elif line.startswith(".func"):
                _, name, nargs, nlocals = line.split()
                cur = Func(name, int(nargs), int(nlocals))
                funcs.append(cur)
            elif line == ".endfunc":
                cur = None
            elif line.endswith(":"):
                cur.labels[line[:-1]] = len(cur.lines)
            else:
                parts = line.split()
                cur.lines.append((lineno, parts[0].lower(), parts[1:]))
    return globals_count, funcs


def assemble(globals_count, funcs):
    func_index = {f.name: i for i, f in enumerate(funcs)}
    header_size = 2 + 4 * len(funcs)
    code = bytearray()
    offsets = []

    for f in funcs:
        start = header_size + len(code)
        offsets.append(start)
        # instruction index -> byte offset within the function
        pos = []
        size = 0
        for _, op, _ in f.lines:
            pos.append(size)
            size += SIZES.get(op, 1)
        pos.append(size)
        label_off = {name: pos[idx] for name, idx in f.labels.items()}

        body = bytearray()
        for i, (lineno, op, args) in enumerate(f.lines):
            if op not in OPCODES:
                raise SystemExit("line %d: unknown op %s" % (lineno, op))
            body.append(OPCODES[op])
            if op == "pushi":
                a = args[0]
                value = func_index[a[1:]] if a.startswith("@") else int(a, 0)
                body += struct.pack("<i", value)
            elif op == "pushf":
                body += struct.pack("<f", float(args[0]))
            elif op in ("ldg", "stg", "ldl", "stl"):
                body.append(int(args[0]))
            elif op in ("jmp", "jz", "jnz"):
                target = label_off[args[0]]
                rel = target - (pos[i] + 3)
                body += struct.pack("<h", rel)
            elif op == "call":
                body.append(func_index[args[0]])
            elif op == "native":
                body.append(NATIVES.index(args[0]))
                body.append(int(args[1]))
        assert len(body) == size
        code += body

    out = bytearray([len(funcs), globals_count])
    for f, off in zip(funcs, offsets):
        out += struct.pack("<HBB", off, f.nargs, f.nlocals)
    return bytes(out + code)


def emit(blob, path):
    lines = [
        "// Generated by tools/script_asm.py from tools/map_script.asm - do not edit.",
        "",
        '#include "Game.h"',
        "",
        "const u8 g_mapScript[] =",
        "{",
    ]
    for i in range(0, len(blob), 16):
        chunk = ", ".join("0x%02X" % b for b in blob[i:i + 16])
        lines.append("    " + chunk + ",")
    lines += ["};", "", "const u32 g_mapScriptSize = sizeof(g_mapScript);", ""]
    with open(path, "w", newline="\n") as f:
        f.write("\n".join(lines))


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    globals_count, funcs = parse(sys.argv[1])
    blob = assemble(globals_count, funcs)
    emit(blob, sys.argv[2])
    print("%d functions, %d bytes" % (len(funcs), len(blob)))


if __name__ == "__main__":
    main()
